services:
    netgen_layouts.ibexa.search.persistence.criterion_handler.is_component_used:
        parent: Ibexa\Core\Search\Legacy\Content\Common\Gateway\CriterionHandler
        class: Netgen\Layouts\Ibexa\Search\Persistence\CriterionHandler\IsComponentUsed
        tags:
            - { name: ibexa.search.legacy.gateway.criterion_handler.content }
            - { name: ibexa.search.legacy.gateway.criterion_handler.location }
